### PR TITLE
`build-abc.sh`: Add AArch64 macOS configuration

### LINKED ISSUE #20: Does not build on AArch64
Attempting to build `abcBridge` on Apple silicon (or any other AArch64 machine, presumably) yields the following error:

```
$ cabal build
HEAD is now at f8d96d7 Allow building with GHC 9.10
Configuration is affected by the following files:
- cabal.project
- cabal.project.local
Build profile: -w ghc-9.4.8 -O1
In order, the following will be built (use -v for more details):
 - abcBridge-0.17.1 (lib:abcBridge) (first run)
Warning: abcBridge.cabal:15:28: Packages with 'cabal-version: 1.12' or later
should specify a specific version of the Cabal spec of the form
'cabal-version: x.y'. Use 'cabal-version: 1.18'.
Cabal library version: 3.8.1.0
Using libabc [to be built] in abc-build
Unknown architecture: AArch64
Error: [Cabal-7125]
Failed to build abcBridge-0.17.1. The failure occurred during the configure step. The build process terminated with exit code 2
```

### PR DESCRIPTION
**Pull request by RyanGlScott**
Fixes #20.

### CODE REVIEW

File: scripts/build-abc.sh [hunk 1]
```diff
@@ -20,6 +20,7 @@ case "$OS" in
     case "$ARCH" in
       "I386") A="-m32 -DLIN -DSIZEOF_VOID_P=4 -DSIZEOF_LONG=4 -DSIZEOF_INT=4" ;;
       "X86_64") A="-m64 -fPIC -DLIN64 -DSIZEOF_VOID_P=8 -DSIZEOF_LONG=8 -DSIZEOF_INT=4" ;;
+      "AArch64") A="-m64 -fPIC -DLIN64 -DSIZEOF_VOID_P=8 -DSIZEOF_LONG=8 -DSIZEOF_INT=4" ;;
```
Comment (kquick) [inline scripts/build-abc.sh:23]: `-DLIN64` looks suspicious if you are targeting MacOS, but I'm good with this if you are.

**Review by kquick — APPROVED** [review]

File: scripts/build-abc.sh (hunk 1 above)
Comment (RyanGlScott) [reply scripts/build-abc.sh:23]: I thought so too! But interestingly, that is what `abc` itself reports. Specifically, if you compile `abc`'s [`arch_flags`](https://github.com/berkeley-abc/abc/blob/4656ae10e08a086d111e6982f057d18babad1150/arch_flags.c) script and run it on Apple silicon, then it reports the following:

```
$ ./arch_flags
-DLIN64 -DSIZEOF_VOID_P=8 -DSIZEOF_LONG=8 -DSIZEOF_INT=4
```

If `abc` itself recommends `-DLIN64`, then I'm happy to oblige :)
